// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Result holds the optimized output and size comparison.
 */
export class Result {
    "optimized": string;
    "beforeBytes": number;
    "afterBytes": number;

    /**
     * formatted with 2 decimals
     */
    "reductionPct": string;

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("optimized" in $$source)) {
            this["optimized"] = "";
        }
        if (!("beforeBytes" in $$source)) {
            this["beforeBytes"] = 0;
        }
        if (!("afterBytes" in $$source)) {
            this["afterBytes"] = 0;
        }
        if (!("reductionPct" in $$source)) {
            this["reductionPct"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Result($$parsedSource as Partial<Result>);
    }
}
