// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Options configures the diff.
 */
export class Options {
    /**
     * "line" (default) | "char"
     */
    "mode": string;

    /**
     * normalize both sides as JSON first
     */
    "jsonMode": boolean;

    /** Creates a new Options instance. */
    constructor($$source: Partial<Options> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("jsonMode" in $$source)) {
            this["jsonMode"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Options instance from a string or object.
     */
    static createFrom($$source: any = {}): Options {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Options($$parsedSource as Partial<Options>);
    }
}

/**
 * Result holds side-by-side segments. Left carries equal+delete; Right carries equal+insert.
 */
export class Result {
    "left": Segment[];
    "right": Segment[];
    "identical": boolean;

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("left" in $$source)) {
            this["left"] = [];
        }
        if (!("right" in $$source)) {
            this["right"] = [];
        }
        if (!("identical" in $$source)) {
            this["identical"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("left" in $$parsedSource) {
            $$parsedSource["left"] = $$createField0_0($$parsedSource["left"]);
        }
        if ("right" in $$parsedSource) {
            $$parsedSource["right"] = $$createField1_0($$parsedSource["right"]);
        }
        return new Result($$parsedSource as Partial<Result>);
    }
}

/**
 * Segment is a contiguous run tagged by its diff type.
 */
export class Segment {
    /**
     * "equal" | "insert" | "delete"
     */
    "type": string;
    "text": string;

    /** Creates a new Segment instance. */
    constructor($$source: Partial<Segment> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Segment instance from a string or object.
     */
    static createFrom($$source: any = {}): Segment {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Segment($$parsedSource as Partial<Segment>);
    }
}

// Private type creation functions
const $$createType0 = Segment.createFrom;
const $$createType1 = $Create.Array($$createType0);
