// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BatchItemStatus is the per-source state within a batch conversion.
 */
export class BatchItemStatus {
    "source": string;
    "output": string;

    /**
     * Name is the display base name (without directory) of the output file.
     */
    "name": string;

    /**
     * Percent is 0-100 for the item, or -1 when its duration is unknown.
     */
    "percent": number;

    /**
     * Duration is the item's media length in seconds (0 when unknown).
     */
    "duration": number;

    /**
     * Speed is the current encoding speed relative to realtime (e.g. 12 = 12x).
     */
    "speed": number;

    /**
     * ETA is the estimated seconds remaining for this item; -1 when unknown.
     */
    "eta": number;

    /**
     * Started is true once the item's conversion has begun (it may run in
     * parallel with others).
     */
    "started": boolean;
    "done": boolean;
    "success": boolean;
    "error": string;

    /** Creates a new BatchItemStatus instance. */
    constructor($$source: Partial<BatchItemStatus> = {}) {
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("percent" in $$source)) {
            this["percent"] = 0;
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("speed" in $$source)) {
            this["speed"] = 0;
        }
        if (!("eta" in $$source)) {
            this["eta"] = 0;
        }
        if (!("started" in $$source)) {
            this["started"] = false;
        }
        if (!("done" in $$source)) {
            this["done"] = false;
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchItemStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): BatchItemStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BatchItemStatus($$parsedSource as Partial<BatchItemStatus>);
    }
}

/**
 * BatchProgress is an immutable snapshot of a batch conversion.
 */
export class BatchProgress {
    "total": number;

    /**
     * items finished (success or failure)
     */
    "completed": number;
    "succeeded": number;
    "failed": number;

    /**
     * items currently converting in parallel
     */
    "running": number;
    "items": BatchItemStatus[];

    /**
     * Percent is the overall progress 0-100. It is duration-weighted when every
     * item's length is known, otherwise it falls back to a per-item count.
     */
    "percent": number;

    /**
     * ETA is the estimated seconds remaining for the whole batch; -1 when unknown.
     */
    "eta": number;

    /**
     * Elapsed is the wall-clock seconds since the batch started.
     */
    "elapsed": number;
    "done": boolean;
    "canceled": boolean;

    /** Creates a new BatchProgress instance. */
    constructor($$source: Partial<BatchProgress> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("completed" in $$source)) {
            this["completed"] = 0;
        }
        if (!("succeeded" in $$source)) {
            this["succeeded"] = 0;
        }
        if (!("failed" in $$source)) {
            this["failed"] = 0;
        }
        if (!("running" in $$source)) {
            this["running"] = 0;
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("percent" in $$source)) {
            this["percent"] = 0;
        }
        if (!("eta" in $$source)) {
            this["eta"] = 0;
        }
        if (!("elapsed" in $$source)) {
            this["elapsed"] = 0;
        }
        if (!("done" in $$source)) {
            this["done"] = false;
        }
        if (!("canceled" in $$source)) {
            this["canceled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): BatchProgress {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField5_0($$parsedSource["items"]);
        }
        return new BatchProgress($$parsedSource as Partial<BatchProgress>);
    }
}

/**
 * Container identifies the target output format.
 */
export enum Container {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MP4 = "mp4",
    MKV = "mkv",
    MOV = "mov",
    TS = "ts",

    /**
     * audio-only extraction
     */
    MP3 = "mp3",
};

/**
 * FFmpegInfo reports whether ffmpeg is available and, if so, its location and
 * version banner. The frontend uses this to guide the user through installing
 * ffmpeg when it is missing.
 */
export class FFmpegInfo {
    "available": boolean;
    "path": string;
    "version": string;

    /**
     * OS is the current platform (runtime.GOOS), so the UI can highlight the
     * matching install instructions.
     */
    "os": string;

    /**
     * InstallCmd is the recommended one-line install command for this platform.
     */
    "installCmd": string;

    /**
     * DownloadURL points to the official ffmpeg download page as a fallback.
     */
    "downloadURL": string;

    /**
     * HWEncoder is the detected, validated hardware H.264 encoder (e.g.
     * "h264_videotoolbox"); empty when none is usable. Only meaningful when
     * Available is true. The UI uses it to offer hardware-accelerated encoding.
     */
    "hwEncoder": string;

    /** Creates a new FFmpegInfo instance. */
    constructor($$source: Partial<FFmpegInfo> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("os" in $$source)) {
            this["os"] = "";
        }
        if (!("installCmd" in $$source)) {
            this["installCmd"] = "";
        }
        if (!("downloadURL" in $$source)) {
            this["downloadURL"] = "";
        }
        if (!("hwEncoder" in $$source)) {
            this["hwEncoder"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FFmpegInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): FFmpegInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FFmpegInfo($$parsedSource as Partial<FFmpegInfo>);
    }
}

/**
 * Options configures a conversion job.
 */
export class Options {
    /**
     * Format is the target container (mp4/mkv/mov/ts/mp3).
     */
    "format": Container;

    /**
     * ReEncode transcodes to H.264/AAC instead of copying streams. Slower, but
     * resolves codec/container incompatibilities. Ignored for audio-only output.
     */
    "reEncode": boolean;

    /**
     * HWAccel uses a hardware video encoder (VideoToolbox/NVENC/QSV/AMF) when
     * re-encoding, which is much faster and offloads the CPU. Ignored unless
     * ReEncode is set; falls back to software when no hardware encoder is usable.
     */
    "hwAccel": boolean;

    /** Creates a new Options instance. */
    constructor($$source: Partial<Options> = {}) {
        if (!("format" in $$source)) {
            this["format"] = Container.$zero;
        }
        if (!("reEncode" in $$source)) {
            this["reEncode"] = false;
        }
        if (!("hwAccel" in $$source)) {
            this["hwAccel"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Options instance from a string or object.
     */
    static createFrom($$source: any = {}): Options {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Options($$parsedSource as Partial<Options>);
    }
}

/**
 * ProbeResult summarizes an m3u8 playlist before conversion.
 */
export class ProbeResult {
    /**
     * Master is true when the playlist lists variant streams rather than segments.
     */
    "master": boolean;

    /**
     * Duration is the total media length in seconds (0 when unknown, e.g. for
     * master playlists or live streams).
     */
    "duration": number;

    /**
     * Segments counts the media segments in the (resolved) media playlist.
     */
    "segments": number;

    /**
     * Encrypted is true when the playlist declares AES-128 segment encryption.
     */
    "encrypted": boolean;

    /**
     * Live is true when the playlist has no #EXT-X-ENDLIST marker.
     */
    "live": boolean;

    /** Creates a new ProbeResult instance. */
    constructor($$source: Partial<ProbeResult> = {}) {
        if (!("master" in $$source)) {
            this["master"] = false;
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("segments" in $$source)) {
            this["segments"] = 0;
        }
        if (!("encrypted" in $$source)) {
            this["encrypted"] = false;
        }
        if (!("live" in $$source)) {
            this["live"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProbeResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ProbeResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProbeResult($$parsedSource as Partial<ProbeResult>);
    }
}

// Private type creation functions
const $$createType0 = BatchItemStatus.createFrom;
const $$createType1 = $Create.Array($$createType0);
