// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Result holds the decoded, formatted JWT parts.
 */
export class Result {
    "header": string;
    "payload": string;

    /**
     * empty when no exp
     */
    "expHuman": string;

    /**
     * nil when no exp
     */
    "expired": boolean | null;

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("header" in $$source)) {
            this["header"] = "";
        }
        if (!("payload" in $$source)) {
            this["payload"] = "";
        }
        if (!("expHuman" in $$source)) {
            this["expHuman"] = "";
        }
        if (!("expired" in $$source)) {
            this["expired"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Result($$parsedSource as Partial<Result>);
    }
}
