// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Options configures generation.
 */
export class Options {
    /**
     * hex like #000000
     */
    "foreground": string;

    /**
     * hex like #ffffff
     */
    "background": string;

    /**
     * pixel dimensions
     */
    "size": number;

    /** Creates a new Options instance. */
    constructor($$source: Partial<Options> = {}) {
        if (!("foreground" in $$source)) {
            this["foreground"] = "";
        }
        if (!("background" in $$source)) {
            this["background"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Options instance from a string or object.
     */
    static createFrom($$source: any = {}): Options {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Options($$parsedSource as Partial<Options>);
    }
}
