// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Perms represents the three permission triads.
 */
export class Perms {
    "owner": Triad;
    "group": Triad;
    "other": Triad;

    /** Creates a new Perms instance. */
    constructor($$source: Partial<Perms> = {}) {
        if (!("owner" in $$source)) {
            this["owner"] = (new Triad());
        }
        if (!("group" in $$source)) {
            this["group"] = (new Triad());
        }
        if (!("other" in $$source)) {
            this["other"] = (new Triad());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Perms instance from a string or object.
     */
    static createFrom($$source: any = {}): Perms {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("owner" in $$parsedSource) {
            $$parsedSource["owner"] = $$createField0_0($$parsedSource["owner"]);
        }
        if ("group" in $$parsedSource) {
            $$parsedSource["group"] = $$createField1_0($$parsedSource["group"]);
        }
        if ("other" in $$parsedSource) {
            $$parsedSource["other"] = $$createField2_0($$parsedSource["other"]);
        }
        return new Perms($$parsedSource as Partial<Perms>);
    }
}

/**
 * Result bundles all representations.
 */
export class Result {
    /**
     * e.g. "755"
     */
    "numeric": string;

    /**
     * e.g. "rwxr-xr-x"
     */
    "symbolic": string;
    "perms": Perms;

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("numeric" in $$source)) {
            this["numeric"] = "";
        }
        if (!("symbolic" in $$source)) {
            this["symbolic"] = "";
        }
        if (!("perms" in $$source)) {
            this["perms"] = (new Perms());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("perms" in $$parsedSource) {
            $$parsedSource["perms"] = $$createField2_0($$parsedSource["perms"]);
        }
        return new Result($$parsedSource as Partial<Result>);
    }
}

/**
 * Triad is a single read/write/execute group.
 */
export class Triad {
    "read": boolean;
    "write": boolean;
    "exec": boolean;

    /** Creates a new Triad instance. */
    constructor($$source: Partial<Triad> = {}) {
        if (!("read" in $$source)) {
            this["read"] = false;
        }
        if (!("write" in $$source)) {
            this["write"] = false;
        }
        if (!("exec" in $$source)) {
            this["exec"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Triad instance from a string or object.
     */
    static createFrom($$source: any = {}): Triad {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Triad($$parsedSource as Partial<Triad>);
    }
}

// Private type creation functions
const $$createType0 = Triad.createFrom;
const $$createType1 = Perms.createFrom;
