// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Pick is the color sampled under the cursor plus a small zoomed region used by
 * the frontend magnifier loupe.
 */
export class Pick {
    "hex": string;
    "r": number;
    "g": number;
    "b": number;

    /**
     * cursor position (display points)
     */
    "x": number;
    "y": number;

    /**
     * side length (px) of the loupe region
     */
    "region": number;

    /**
     * PNG of the region for magnification
     */
    "dataUri": string;

    /** Creates a new Pick instance. */
    constructor($$source: Partial<Pick> = {}) {
        if (!("hex" in $$source)) {
            this["hex"] = "";
        }
        if (!("r" in $$source)) {
            this["r"] = 0;
        }
        if (!("g" in $$source)) {
            this["g"] = 0;
        }
        if (!("b" in $$source)) {
            this["b"] = 0;
        }
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("region" in $$source)) {
            this["region"] = 0;
        }
        if (!("dataUri" in $$source)) {
            this["dataUri"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Pick instance from a string or object.
     */
    static createFrom($$source: any = {}): Pick {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Pick($$parsedSource as Partial<Pick>);
    }
}
