// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Flags toggles regex modifiers.
 */
export class Flags {
    "global": boolean;
    "ignoreCase": boolean;
    "multiline": boolean;

    /** Creates a new Flags instance. */
    constructor($$source: Partial<Flags> = {}) {
        if (!("global" in $$source)) {
            this["global"] = false;
        }
        if (!("ignoreCase" in $$source)) {
            this["ignoreCase"] = false;
        }
        if (!("multiline" in $$source)) {
            this["multiline"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Flags instance from a string or object.
     */
    static createFrom($$source: any = {}): Flags {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Flags($$parsedSource as Partial<Flags>);
    }
}

/**
 * Match describes a single match and its capture groups.
 */
export class Match {
    "text": string;
    "start": number;
    "end": number;
    "groups": string[];

    /** Creates a new Match instance. */
    constructor($$source: Partial<Match> = {}) {
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("start" in $$source)) {
            this["start"] = 0;
        }
        if (!("end" in $$source)) {
            this["end"] = 0;
        }
        if (!("groups" in $$source)) {
            this["groups"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Match instance from a string or object.
     */
    static createFrom($$source: any = {}): Match {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField3_0($$parsedSource["groups"]);
        }
        return new Match($$parsedSource as Partial<Match>);
    }
}

/**
 * Preset is a named entry from the common regex library.
 */
export class Preset {
    "name": string;
    "pattern": string;

    /** Creates a new Preset instance. */
    constructor($$source: Partial<Preset> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("pattern" in $$source)) {
            this["pattern"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Preset instance from a string or object.
     */
    static createFrom($$source: any = {}): Preset {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Preset($$parsedSource as Partial<Preset>);
    }
}

/**
 * Result holds all matches.
 */
export class Result {
    "matches": Match[];
    "count": number;

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("matches" in $$source)) {
            this["matches"] = [];
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("matches" in $$parsedSource) {
            $$parsedSource["matches"] = $$createField0_0($$parsedSource["matches"]);
        }
        return new Result($$parsedSource as Partial<Result>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Match.createFrom;
const $$createType2 = $Create.Array($$createType1);
