// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Charset describes which character classes feed the brute-force generator.
 */
export class Charset {
    /**
     * a-z
     */
    "lower": boolean;

    /**
     * A-Z
     */
    "upper": boolean;

    /**
     * 0-9
     */
    "digits": boolean;

    /**
     * common ASCII symbols
     */
    "symbols": boolean;

    /**
     * extra characters to include
     */
    "custom": string;

    /** Creates a new Charset instance. */
    constructor($$source: Partial<Charset> = {}) {
        if (!("lower" in $$source)) {
            this["lower"] = false;
        }
        if (!("upper" in $$source)) {
            this["upper"] = false;
        }
        if (!("digits" in $$source)) {
            this["digits"] = false;
        }
        if (!("symbols" in $$source)) {
            this["symbols"] = false;
        }
        if (!("custom" in $$source)) {
            this["custom"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Charset instance from a string or object.
     */
    static createFrom($$source: any = {}): Charset {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Charset($$parsedSource as Partial<Charset>);
    }
}

/**
 * Format identifies the container type being attacked.
 */
export enum Format {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FormatAuto = "auto",
    FormatZIP = "zip",
    FormatPDF = "pdf",

    /**
     * docx / xlsx / pptx (OOXML, OLE-encrypted)
     */
    FormatOffice = "office",
};

/**
 * Mode selects the candidate-generation strategy.
 */
export enum Mode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * charset + length range
     */
    ModeBrute = "brute",

    /**
     * user-supplied wordlist
     */
    ModeDict = "dict",
};

/**
 * Options configures a cracking job.
 */
export class Options {
    "format": Format;
    "mode": Mode;
    "minLen": number;
    "maxLen": number;
    "charset": Charset;

    /**
     * newline-separated, for ModeDict
     */
    "wordlist": string;

    /** Creates a new Options instance. */
    constructor($$source: Partial<Options> = {}) {
        if (!("format" in $$source)) {
            this["format"] = Format.$zero;
        }
        if (!("mode" in $$source)) {
            this["mode"] = Mode.$zero;
        }
        if (!("minLen" in $$source)) {
            this["minLen"] = 0;
        }
        if (!("maxLen" in $$source)) {
            this["maxLen"] = 0;
        }
        if (!("charset" in $$source)) {
            this["charset"] = (new Charset());
        }
        if (!("wordlist" in $$source)) {
            this["wordlist"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Options instance from a string or object.
     */
    static createFrom($$source: any = {}): Options {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("charset" in $$parsedSource) {
            $$parsedSource["charset"] = $$createField4_0($$parsedSource["charset"]);
        }
        return new Options($$parsedSource as Partial<Options>);
    }
}

/**
 * Progress is an immutable snapshot of a job's state, returned to the frontend.
 */
export class Progress {
    "tried": number;

    /**
     * -1 when the space is unbounded/too large to count
     */
    "total": number;
    "current": string;
    "found": boolean;
    "password": string;
    "done": boolean;
    "canceled": boolean;
    "error": string;

    /**
     * seconds
     */
    "elapsed": number;

    /**
     * attempts per second
     */
    "rate": number;

    /**
     * estimated seconds remaining; -1 when unknown
     */
    "eta": number;

    /** Creates a new Progress instance. */
    constructor($$source: Partial<Progress> = {}) {
        if (!("tried" in $$source)) {
            this["tried"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("current" in $$source)) {
            this["current"] = "";
        }
        if (!("found" in $$source)) {
            this["found"] = false;
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("done" in $$source)) {
            this["done"] = false;
        }
        if (!("canceled" in $$source)) {
            this["canceled"] = false;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("elapsed" in $$source)) {
            this["elapsed"] = 0;
        }
        if (!("rate" in $$source)) {
            this["rate"] = 0;
        }
        if (!("eta" in $$source)) {
            this["eta"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Progress instance from a string or object.
     */
    static createFrom($$source: any = {}): Progress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Progress($$parsedSource as Partial<Progress>);
    }
}

// Private type creation functions
const $$createType0 = Charset.createFrom;
