// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Charset describes which character classes feed the brute-force generator.
 */
export class Charset {
    /**
     * a-z
     */
    "lower": boolean;

    /**
     * A-Z
     */
    "upper": boolean;

    /**
     * 0-9
     */
    "digits": boolean;

    /**
     * common ASCII symbols
     */
    "symbols": boolean;

    /**
     * extra characters to include
     */
    "custom": string;

    /** Creates a new Charset instance. */
    constructor($$source: Partial<Charset> = {}) {
        if (!("lower" in $$source)) {
            this["lower"] = false;
        }
        if (!("upper" in $$source)) {
            this["upper"] = false;
        }
        if (!("digits" in $$source)) {
            this["digits"] = false;
        }
        if (!("symbols" in $$source)) {
            this["symbols"] = false;
        }
        if (!("custom" in $$source)) {
            this["custom"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Charset instance from a string or object.
     */
    static createFrom($$source: any = {}): Charset {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Charset($$parsedSource as Partial<Charset>);
    }
}

/**
 * DecryptedEntry is one decrypted file recovered from an archive.
 */
export class DecryptedEntry {
    "name": string;
    "content": string;

    /** Creates a new DecryptedEntry instance. */
    constructor($$source: Partial<DecryptedEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DecryptedEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): DecryptedEntry {
        const $$createField1_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("content" in $$parsedSource) {
            $$parsedSource["content"] = $$createField1_0($$parsedSource["content"]);
        }
        return new DecryptedEntry($$parsedSource as Partial<DecryptedEntry>);
    }
}

/**
 * Format identifies the container type being attacked.
 */
export enum Format {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FormatAuto = "auto",
    FormatZIP = "zip",
    FormatPDF = "pdf",

    /**
     * docx / xlsx / pptx (OOXML, OLE-encrypted)
     */
    FormatOffice = "office",
};

/**
 * KPAPhase identifies which stage a known-plaintext attack job is in.
 */
export enum KPAPhase {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * narrowing key2 candidates
     */
    KPAPhaseReducing = "reducing",

    /**
     * testing candidates for full keys
     */
    KPAPhaseAttacking = "attacking",

    /**
     * decrypting archive with recovered keys
     */
    KPAPhaseDecrypting = "decrypting",
    KPAPhaseDone = "done",
};

/**
 * KPAProgress is an immutable snapshot of a known-plaintext attack job.
 */
export class KPAProgress {
    "phase": KPAPhase;
    "done": number;
    "total": number;

    /**
     * seconds
     */
    "elapsed": number;
    "finished": boolean;
    "found": boolean;

    /**
     * hex keys when found
     */
    "keys": string;

    /**
     * decrypted entries when finished
     */
    "fileCount": number;
    "canceled": boolean;
    "error": string;

    /** Creates a new KPAProgress instance. */
    constructor($$source: Partial<KPAProgress> = {}) {
        if (!("phase" in $$source)) {
            this["phase"] = KPAPhase.$zero;
        }
        if (!("done" in $$source)) {
            this["done"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("elapsed" in $$source)) {
            this["elapsed"] = 0;
        }
        if (!("finished" in $$source)) {
            this["finished"] = false;
        }
        if (!("found" in $$source)) {
            this["found"] = false;
        }
        if (!("keys" in $$source)) {
            this["keys"] = "";
        }
        if (!("fileCount" in $$source)) {
            this["fileCount"] = 0;
        }
        if (!("canceled" in $$source)) {
            this["canceled"] = false;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KPAProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): KPAProgress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KPAProgress($$parsedSource as Partial<KPAProgress>);
    }
}

/**
 * Mode selects the candidate-generation strategy.
 */
export enum Mode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * charset + length range
     */
    ModeBrute = "brute",

    /**
     * user-supplied wordlist
     */
    ModeDict = "dict",
};

/**
 * Options configures a cracking job.
 */
export class Options {
    "format": Format;
    "mode": Mode;
    "minLen": number;
    "maxLen": number;
    "charset": Charset;

    /**
     * newline-separated, for ModeDict
     */
    "wordlist": string;

    /** Creates a new Options instance. */
    constructor($$source: Partial<Options> = {}) {
        if (!("format" in $$source)) {
            this["format"] = Format.$zero;
        }
        if (!("mode" in $$source)) {
            this["mode"] = Mode.$zero;
        }
        if (!("minLen" in $$source)) {
            this["minLen"] = 0;
        }
        if (!("maxLen" in $$source)) {
            this["maxLen"] = 0;
        }
        if (!("charset" in $$source)) {
            this["charset"] = (new Charset());
        }
        if (!("wordlist" in $$source)) {
            this["wordlist"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Options instance from a string or object.
     */
    static createFrom($$source: any = {}): Options {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("charset" in $$parsedSource) {
            $$parsedSource["charset"] = $$createField4_0($$parsedSource["charset"]);
        }
        return new Options($$parsedSource as Partial<Options>);
    }
}

/**
 * PasswordProgress is a snapshot of a password-recovery job.
 */
export class PasswordProgress {
    "currentLength": number;
    "passwords": string[];
    "elapsed": number;
    "finished": boolean;
    "canceled": boolean;

    /** Creates a new PasswordProgress instance. */
    constructor($$source: Partial<PasswordProgress> = {}) {
        if (!("currentLength" in $$source)) {
            this["currentLength"] = 0;
        }
        if (!("passwords" in $$source)) {
            this["passwords"] = [];
        }
        if (!("elapsed" in $$source)) {
            this["elapsed"] = 0;
        }
        if (!("finished" in $$source)) {
            this["finished"] = false;
        }
        if (!("canceled" in $$source)) {
            this["canceled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PasswordProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): PasswordProgress {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("passwords" in $$parsedSource) {
            $$parsedSource["passwords"] = $$createField1_0($$parsedSource["passwords"]);
        }
        return new PasswordProgress($$parsedSource as Partial<PasswordProgress>);
    }
}

/**
 * PlaintextPrep is the outcome of preparing known plaintext from an original
 * file. Plaintext is the (compressed) bytes to feed the attack.
 */
export class PlaintextPrep {
    "plaintext": string;
    "offset": number;

    /**
     * 0 = Store, 8 = Deflate
     */
    "method": number;

    /**
     * true when the entry is uncompressed
     */
    "stored": boolean;

    /**
     * the original file's CRC-32 matches the entry
     */
    "crcMatch": boolean;

    /**
     * the (re)compressed length matches the entry
     */
    "lengthMatch": boolean;

    /**
     * safe to launch the attack directly
     */
    "ready": boolean;

    /**
     * human-readable guidance
     */
    "message": string;

    /** Creates a new PlaintextPrep instance. */
    constructor($$source: Partial<PlaintextPrep> = {}) {
        if (!("plaintext" in $$source)) {
            this["plaintext"] = "";
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("method" in $$source)) {
            this["method"] = 0;
        }
        if (!("stored" in $$source)) {
            this["stored"] = false;
        }
        if (!("crcMatch" in $$source)) {
            this["crcMatch"] = false;
        }
        if (!("lengthMatch" in $$source)) {
            this["lengthMatch"] = false;
        }
        if (!("ready" in $$source)) {
            this["ready"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaintextPrep instance from a string or object.
     */
    static createFrom($$source: any = {}): PlaintextPrep {
        const $$createField0_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("plaintext" in $$parsedSource) {
            $$parsedSource["plaintext"] = $$createField0_0($$parsedSource["plaintext"]);
        }
        return new PlaintextPrep($$parsedSource as Partial<PlaintextPrep>);
    }
}

/**
 * Progress is an immutable snapshot of a job's state, returned to the frontend.
 */
export class Progress {
    "tried": number;

    /**
     * -1 when the space is unbounded/too large to count
     */
    "total": number;
    "current": string;
    "found": boolean;
    "password": string;
    "done": boolean;
    "canceled": boolean;
    "error": string;

    /**
     * seconds
     */
    "elapsed": number;

    /**
     * attempts per second
     */
    "rate": number;

    /**
     * estimated seconds remaining; -1 when unknown
     */
    "eta": number;

    /**
     * candidates skipped because the job resumed a checkpoint
     */
    "resumedFrom": number;

    /** Creates a new Progress instance. */
    constructor($$source: Partial<Progress> = {}) {
        if (!("tried" in $$source)) {
            this["tried"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("current" in $$source)) {
            this["current"] = "";
        }
        if (!("found" in $$source)) {
            this["found"] = false;
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("done" in $$source)) {
            this["done"] = false;
        }
        if (!("canceled" in $$source)) {
            this["canceled"] = false;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("elapsed" in $$source)) {
            this["elapsed"] = 0;
        }
        if (!("rate" in $$source)) {
            this["rate"] = 0;
        }
        if (!("eta" in $$source)) {
            this["eta"] = 0;
        }
        if (!("resumedFrom" in $$source)) {
            this["resumedFrom"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Progress instance from a string or object.
     */
    static createFrom($$source: any = {}): Progress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Progress($$parsedSource as Partial<Progress>);
    }
}

/**
 * ResumeInfo describes a previously-saved checkpoint that a new job can continue.
 */
export class ResumeInfo {
    "available": boolean;
    "tried": number;
    "total": number;

    /** Creates a new ResumeInfo instance. */
    constructor($$source: Partial<ResumeInfo> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("tried" in $$source)) {
            this["tried"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResumeInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ResumeInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResumeInfo($$parsedSource as Partial<ResumeInfo>);
    }
}

/**
 * ZipEncryption identifies the scheme protecting a single ZIP entry.
 */
export enum ZipEncryption {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ZipEncNone = "none",

    /**
     * ZipEncZipCrypto is traditional PKWARE (ZipCrypto) encryption. It is the
     * only scheme vulnerable to the Biham–Kocher known-plaintext attack.
     */
    ZipEncZipCrypto = "zipcrypto",
    ZipEncAES128 = "aes128",
    ZipEncAES192 = "aes192",
    ZipEncAES256 = "aes256",

    /**
     * ZipEncAESOther is a WinZip AES entry whose strength byte is unrecognized.
     */
    ZipEncAESOther = "aes",
};

/**
 * ZipEntryInfo describes one entry's encryption.
 */
export class ZipEntryInfo {
    "name": string;
    "encrypted": boolean;
    "encryption": ZipEncryption;

    /** Creates a new ZipEntryInfo instance. */
    constructor($$source: Partial<ZipEntryInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("encrypted" in $$source)) {
            this["encrypted"] = false;
        }
        if (!("encryption" in $$source)) {
            this["encryption"] = ZipEncryption.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ZipEntryInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ZipEntryInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ZipEntryInfo($$parsedSource as Partial<ZipEntryInfo>);
    }
}

/**
 * ZipInfo summarizes the encryption used across a ZIP archive.
 */
export class ZipInfo {
    "entries": ZipEntryInfo[];

    /**
     * at least one encrypted entry
     */
    "encrypted": boolean;

    /**
     * at least one ZipCrypto entry
     */
    "hasZipCrypto": boolean;

    /**
     * at least one AES entry
     */
    "hasAES": boolean;

    /** Creates a new ZipInfo instance. */
    constructor($$source: Partial<ZipInfo> = {}) {
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }
        if (!("encrypted" in $$source)) {
            this["encrypted"] = false;
        }
        if (!("hasZipCrypto" in $$source)) {
            this["hasZipCrypto"] = false;
        }
        if (!("hasAES" in $$source)) {
            this["hasAES"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ZipInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ZipInfo {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField0_0($$parsedSource["entries"]);
        }
        return new ZipInfo($$parsedSource as Partial<ZipInfo>);
    }
}

// Private type creation functions
const $$createType0 = Charset.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = ZipEntryInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
