// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CodecService exposes basic encoding/transcoding (R17) and hashing/symmetric
 * encryption (R18) to the frontend. All processing is local.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Decode decodes input using the given kind ("base64" | "url" | "hex" | "unicode").
 */
export function Decode(input: string, kind: string): $CancellablePromise<string> {
    return $Call.ByID(559761613, input, kind);
}

/**
 * Decrypt reverses Encrypt; a wrong key fails authentication.
 */
export function Decrypt(ciphertext: string, key: string): $CancellablePromise<string> {
    return $Call.ByID(885458284, ciphertext, key);
}

/**
 * Encode encodes input using the given kind ("base64" | "url" | "hex" | "unicode").
 */
export function Encode(input: string, kind: string): $CancellablePromise<string> {
    return $Call.ByID(3030620649, input, kind);
}

/**
 * Encrypt performs AES-GCM encryption; the key must be 16, 24 or 32 bytes.
 */
export function Encrypt(plain: string, key: string): $CancellablePromise<string> {
    return $Call.ByID(1496066656, plain, key);
}

/**
 * Hash returns the lowercase hex digest using algo ("md5" | "sha1" | "sha256").
 */
export function Hash(input: string, algo: string): $CancellablePromise<string> {
    return $Call.ByID(3921574027, input, algo);
}
