// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DevOpsService exposes Cron (R9), Chmod (R10) and Env/Path (R11). All local.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as chmod$0 from "./internal/pkg/chmod/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as cronx$0 from "./internal/pkg/cronx/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pathx$0 from "./internal/pkg/pathx/models.js";

/**
 * BuildCron assembles a 5-field cron expression from visual field selections.
 */
export function BuildCron(f: cronx$0.Fields): $CancellablePromise<string> {
    return $Call.ByID(2067891872, f);
}

/**
 * ChmodFromNumeric converts a numeric permission value to symbolic + checkbox state.
 */
export function ChmodFromNumeric(numeric: string): $CancellablePromise<chmod$0.Result> {
    return $Call.ByID(3268717368, numeric).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ChmodFromPerms converts checkbox state to numeric + symbolic representations.
 */
export function ChmodFromPerms(p: chmod$0.Perms): $CancellablePromise<chmod$0.Result> {
    return $Call.ByID(2185151032, p).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ComparePath classifies entries as left-only / right-only / shared.
 */
export function ComparePath(a: string, b: string): $CancellablePromise<pathx$0.DiffEntry[]> {
    return $Call.ByID(4189341172, a, b).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * DedupPath removes duplicate entries, keeping first occurrence.
 */
export function DedupPath(entries: string[]): $CancellablePromise<string[]> {
    return $Call.ByID(1147341923, entries).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * JoinPath recombines entries into a single PATH string.
 */
export function JoinPath(entries: string[]): $CancellablePromise<string> {
    return $Call.ByID(10959651, entries);
}

/**
 * ParseCron validates an expression and returns its description and next 5 runs.
 */
export function ParseCron(expr: string): $CancellablePromise<cronx$0.Info> {
    return $Call.ByID(2055138559, expr).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * SplitPath splits a PATH string into ordered entries.
 */
export function SplitPath(raw: string): $CancellablePromise<string[]> {
    return $Call.ByID(2229272875, raw).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = chmod$0.Result.createFrom;
const $$createType1 = pathx$0.DiffEntry.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = cronx$0.Info.createFrom;
