// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FrontendService exposes color conversion (R12), SVG optimization (R13) and
 * QR code generation/decoding (R14). All processing is local.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as colorx$0 from "./internal/pkg/colorx/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as qrx$0 from "./internal/pkg/qrx/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as svgopt$0 from "./internal/pkg/svgopt/models.js";

/**
 * ConvertColor parses value in the given format ("hex" | "rgb" | "rgba" | "hsl")
 * and returns all four representations.
 */
export function ConvertColor(value: string, format: string): $CancellablePromise<colorx$0.ColorSet> {
    return $Call.ByID(2724514583, value, format).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DecodeQR decodes a QR code from raw PNG/JPEG image bytes.
 */
export function DecodeQR(imageBytes: string): $CancellablePromise<string> {
    return $Call.ByID(1448062848, imageBytes);
}

/**
 * GenerateQR returns a base64 PNG data URI for the given text.
 */
export function GenerateQR(text: string, opts: qrx$0.Options): $CancellablePromise<string> {
    return $Call.ByID(3743551513, text, opts);
}

/**
 * OptimizeSVG minifies SVG markup and reports the size delta.
 */
export function OptimizeSVG(input: string): $CancellablePromise<svgopt$0.Result> {
    return $Call.ByID(636793700, input).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = colorx$0.ColorSet.createFrom;
const $$createType1 = svgopt$0.Result.createFrom;
