// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MediaService exposes batch HLS (m3u8) to MP4/other-container conversion (R19).
 * Conversion is delegated to a locally installed ffmpeg binary; each source may
 * be a remote URL or a local playlist file, and every output is written into a
 * chosen folder keeping the source's base name with the target extension.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mediax$0 from "./internal/pkg/mediax/models.js";

/**
 * BatchItemLog returns the ffmpeg output log captured for the given item within
 * a batch job, so the UI can display it (useful for diagnosing failures).
 */
export function BatchItemLog(id: string, index: number): $CancellablePromise<string> {
    return $Call.ByID(1988326926, id, index);
}

/**
 * BatchProgress returns the latest snapshot for a batch conversion job.
 */
export function BatchProgress(id: string): $CancellablePromise<mediax$0.BatchProgress> {
    return $Call.ByID(2779036788, id).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CancelBatchConvert stops a running batch conversion and forgets it.
 */
export function CancelBatchConvert(id: string): $CancellablePromise<void> {
    return $Call.ByID(2360560608, id);
}

/**
 * CheckFFmpeg reports whether ffmpeg is available so the UI can guide install.
 */
export function CheckFFmpeg(): $CancellablePromise<mediax$0.FFmpegInfo> {
    return $Call.ByID(2802281334).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * PickInputFiles opens a native dialog to choose one or more local .m3u8
 * playlists and returns their paths (empty when the user cancels).
 */
export function PickInputFiles(): $CancellablePromise<string[]> {
    return $Call.ByID(3253989979).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * PickOutputDir opens a native dialog to choose the folder batch results are
 * written to, returning its path (empty when the user cancels).
 */
export function PickOutputDir(): $CancellablePromise<string> {
    return $Call.ByID(1713570772);
}

/**
 * ProbeM3U8 parses the playlist and returns its duration, segment count and
 * encryption/live flags so the user knows what they're about to convert.
 */
export function ProbeM3U8(source: string): $CancellablePromise<mediax$0.ProbeResult> {
    return $Call.ByID(2762249832, source).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * StartBatchConvert converts several m3u8 sources into outputDir, up to
 * concurrency at a time. Each output reuses its source's base name with the
 * target format's extension. It returns a job id to poll with BatchProgress.
 */
export function StartBatchConvert(sources: string[], outputDir: string, opts: mediax$0.Options, concurrency: number): $CancellablePromise<string> {
    return $Call.ByID(530643412, sources, outputDir, opts, concurrency);
}

// Private type creation functions
const $$createType0 = mediax$0.BatchProgress.createFrom;
const $$createType1 = mediax$0.FFmpegInfo.createFrom;
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = mediax$0.ProbeResult.createFrom;
