// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NetworkService exposes URL parsing/rebuilding (R5), cURL conversion (R6) and
 * DNS resolution (R8). The MVP scope is local-only; the HTTP client (R7) is
 * added in a later iteration.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dnsx$0 from "./internal/pkg/dnsx/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as urlparse$0 from "./internal/pkg/urlparse/models.js";

/**
 * BuildURL reassembles a URL from edited parts.
 */
export function BuildURL(parts: urlparse$0.Parts): $CancellablePromise<string> {
    return $Call.ByID(112749814, parts);
}

/**
 * ConvertCurl converts a cURL command into request code for the target language
 * ("python" | "javascript" | "go" | "java").
 */
export function ConvertCurl(cmd: string, target: string): $CancellablePromise<string> {
    return $Call.ByID(3181849444, cmd, target);
}

/**
 * ParseURL decomposes a URL into protocol/host/port/path and query params.
 */
export function ParseURL(raw: string): $CancellablePromise<urlparse$0.Parts> {
    return $Call.ByID(3536905171, raw).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ResolveDNS resolves A/AAAA/CNAME/MX/NS/TXT records for the given host.
 */
export function ResolveDNS(host: string): $CancellablePromise<dnsx$0.Result> {
    return $Call.ByID(3954886000, host).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = urlparse$0.Parts.createFrom;
const $$createType1 = dnsx$0.Result.createFrom;
