// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NetworkService exposes URL parsing/rebuilding (R5) and cURL conversion (R6).
 * The MVP scope is local-only; the HTTP client (R7) and network probe (R8) are
 * added in a later iteration.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as urlparse$0 from "./internal/pkg/urlparse/models.js";

/**
 * BuildURL reassembles a URL from edited parts.
 */
export function BuildURL(parts: urlparse$0.Parts): $CancellablePromise<string> {
    return $Call.ByID(112749814, parts);
}

/**
 * ConvertCurl converts a cURL command into request code for the target language
 * ("python" | "javascript" | "go" | "java").
 */
export function ConvertCurl(cmd: string, target: string): $CancellablePromise<string> {
    return $Call.ByID(3181849444, cmd, target);
}

/**
 * ParseURL decomposes a URL into protocol/host/port/path and query params.
 */
export function ParseURL(raw: string): $CancellablePromise<urlparse$0.Parts> {
    return $Call.ByID(3536905171, raw).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = urlparse$0.Parts.createFrom;
