// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SecurityService exposes JWT decoding (R15) and password/bcrypt generation (R16).
 * All processing is local; plaintext and generated secrets are never logged.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as jwtx$0 from "./internal/pkg/jwtx/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pwdgen$0 from "./internal/pkg/pwdgen/models.js";

/**
 * BcryptHash returns the bcrypt hash of plain.
 */
export function BcryptHash(plain: string): $CancellablePromise<string> {
    return $Call.ByID(1855210469, plain);
}

/**
 * DecodeJWT decodes (without signature verification) and formats a JWT.
 */
export function DecodeJWT(token: string): $CancellablePromise<jwtx$0.Result> {
    return $Call.ByID(1228818590, token).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GeneratePasswords generates Count strong passwords per the given options.
 */
export function GeneratePasswords(opts: pwdgen$0.Options): $CancellablePromise<string[]> {
    return $Call.ByID(1125120762, opts).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = jwtx$0.Result.createFrom;
const $$createType1 = $Create.Array($Create.Any);
