// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SecurityService exposes JWT decoding (R15), password/bcrypt generation (R16)
 * and offline password recovery for encrypted ZIP/PDF/Office files (R17).
 * All processing is local; plaintext and generated secrets are never logged.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as crackx$0 from "./internal/pkg/crackx/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as jwtx$0 from "./internal/pkg/jwtx/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pwdgen$0 from "./internal/pkg/pwdgen/models.js";

/**
 * BcryptHash returns the bcrypt hash of plain.
 */
export function BcryptHash(plain: string): $CancellablePromise<string> {
    return $Call.ByID(1855210469, plain);
}

/**
 * CancelCrack stops a running job and forgets it.
 */
export function CancelCrack(id: string): $CancellablePromise<void> {
    return $Call.ByID(2164633457, id);
}

/**
 * CrackProgress returns the latest progress snapshot for a job.
 */
export function CrackProgress(id: string): $CancellablePromise<crackx$0.Progress> {
    return $Call.ByID(820876228, id).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DecodeJWT decodes (without signature verification) and formats a JWT.
 */
export function DecodeJWT(token: string): $CancellablePromise<jwtx$0.Result> {
    return $Call.ByID(1228818590, token).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GeneratePasswords generates Count strong passwords per the given options.
 */
export function GeneratePasswords(opts: pwdgen$0.Options): $CancellablePromise<string[]> {
    return $Call.ByID(1125120762, opts).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * StartCrack begins an offline password-recovery job over the supplied file
 * bytes and returns a job id used to poll progress. The attack runs in the
 * background so the UI stays responsive.
 */
export function StartCrack(data: string, filename: string, opts: crackx$0.Options): $CancellablePromise<string> {
    return $Call.ByID(4202662565, data, filename, opts);
}

// Private type creation functions
const $$createType0 = crackx$0.Progress.createFrom;
const $$createType1 = jwtx$0.Result.createFrom;
const $$createType2 = $Create.Array($Create.Any);
