// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SecurityService exposes JWT decoding (R15), password/bcrypt generation (R16)
 * and offline password recovery for encrypted ZIP/PDF/Office files (R17).
 * All processing is local; plaintext and generated secrets are never logged.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as crackx$0 from "./internal/pkg/crackx/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as jwtx$0 from "./internal/pkg/jwtx/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pwdgen$0 from "./internal/pkg/pwdgen/models.js";

/**
 * BcryptHash returns the bcrypt hash of plain.
 */
export function BcryptHash(plain: string): $CancellablePromise<string> {
    return $Call.ByID(1855210469, plain);
}

/**
 * CancelCrack stops a running job and forgets it.
 */
export function CancelCrack(id: string): $CancellablePromise<void> {
    return $Call.ByID(2164633457, id);
}

/**
 * CancelKnownPlaintextAttack stops a running KPA job and forgets it.
 */
export function CancelKnownPlaintextAttack(id: string): $CancellablePromise<void> {
    return $Call.ByID(2995156487, id);
}

/**
 * CancelPasswordRecovery stops a running password-recovery job and forgets it.
 */
export function CancelPasswordRecovery(id: string): $CancellablePromise<void> {
    return $Call.ByID(3849054191, id);
}

/**
 * CrackProgress returns the latest progress snapshot for a job.
 */
export function CrackProgress(id: string): $CancellablePromise<crackx$0.Progress> {
    return $Call.ByID(820876228, id).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DecodeJWT decodes (without signature verification) and formats a JWT.
 */
export function DecodeJWT(token: string): $CancellablePromise<jwtx$0.Result> {
    return $Call.ByID(1228818590, token).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GeneratePasswords generates Count strong passwords per the given options.
 */
export function GeneratePasswords(opts: pwdgen$0.Options): $CancellablePromise<string[]> {
    return $Call.ByID(1125120762, opts).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * InspectZip reports the encryption scheme of each entry in a ZIP archive
 * without a password. The frontend uses this to tell ZipCrypto (vulnerable to
 * a known-plaintext attack) apart from AES (which is not) before offering an
 * attack mode.
 */
export function InspectZip(data: string): $CancellablePromise<crackx$0.ZipInfo> {
    return $Call.ByID(1883411132, data).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * KnownPlaintextProgress returns the latest progress snapshot for a KPA job.
 */
export function KnownPlaintextProgress(id: string): $CancellablePromise<crackx$0.KPAProgress> {
    return $Call.ByID(1282061502, id).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * KnownPlaintextResult returns the recovered keys and decrypted entries once a
 * KPA job has finished successfully.
 */
export function KnownPlaintextResult(id: string): $CancellablePromise<crackx$0.DecryptedEntry[]> {
    return $Call.ByID(2599254908, id).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * PasswordRecoveryProgress returns the latest snapshot for a password-recovery job.
 */
export function PasswordRecoveryProgress(id: string): $CancellablePromise<crackx$0.PasswordProgress> {
    return $Call.ByID(4112426158, id).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * PrepareKnownPlaintext turns a user-supplied original file into the known
 * plaintext the attack needs, verifying it via CRC-32 and, for Deflate entries,
 * re-compressing it to match the archive. The returned Plaintext (and Offset)
 * can be passed straight to StartKnownPlaintextAttack.
 */
export function PrepareKnownPlaintext(data: string, entryName: string, rawFile: string): $CancellablePromise<crackx$0.PlaintextPrep> {
    return $Call.ByID(2455678504, data, entryName, rawFile).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * Resumable reports whether a saved checkpoint exists for the given file and
 * options, so the UI can offer to continue a previously interrupted run.
 */
export function Resumable(data: string, filename: string, opts: crackx$0.Options): $CancellablePromise<crackx$0.ResumeInfo> {
    return $Call.ByID(3943579965, data, filename, opts).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * StartCrack begins an offline password-recovery job over the supplied file
 * bytes and returns a job id used to poll progress. The attack runs in the
 * background so the UI stays responsive. When resume is true and a matching
 * checkpoint exists, the job continues from where a previous run stopped.
 */
export function StartCrack(data: string, filename: string, opts: crackx$0.Options, resume: boolean): $CancellablePromise<string> {
    return $Call.ByID(4202662565, data, filename, opts, resume);
}

/**
 * StartKnownPlaintextAttack launches a Biham–Kocher known-plaintext attack
 * against a ZipCrypto entry. plaintext is the known (compressed) bytes of the
 * target entry starting at offset within its data. It returns a job id to poll
 * with KnownPlaintextProgress; on success the recovered keys decrypt every
 * ZipCrypto entry in the archive without the password. Only legacy ZipCrypto is
 * vulnerable — AES entries are rejected.
 */
export function StartKnownPlaintextAttack(data: string, entryName: string, plaintext: string, offset: number): $CancellablePromise<string> {
    return $Call.ByID(2874865531, data, entryName, plaintext, offset);
}

/**
 * StartPasswordRecovery attempts to find a password that yields the keys
 * recovered by a finished known-plaintext attack (kpaId). Recovery is optional:
 * decryption already works with the keys alone. It returns a separate job id to
 * poll with PasswordRecoveryProgress.
 */
export function StartPasswordRecovery(kpaID: string, charset: crackx$0.Charset, minLen: number, maxLen: number): $CancellablePromise<string> {
    return $Call.ByID(1117763315, kpaID, charset, minLen, maxLen);
}

// Private type creation functions
const $$createType0 = crackx$0.Progress.createFrom;
const $$createType1 = jwtx$0.Result.createFrom;
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = crackx$0.ZipInfo.createFrom;
const $$createType4 = crackx$0.KPAProgress.createFrom;
const $$createType5 = crackx$0.DecryptedEntry.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = crackx$0.PasswordProgress.createFrom;
const $$createType8 = crackx$0.PlaintextPrep.createFrom;
const $$createType9 = crackx$0.ResumeInfo.createFrom;
