// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TextService exposes text/JSON diff (R1), regex testing (R3) and mock data (R4). All local.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as differ$0 from "./internal/pkg/differ/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as regexx$0 from "./internal/pkg/regexx/models.js";

/**
 * Diff compares two texts side-by-side, optionally normalizing JSON first.
 */
export function Diff(left: string, right: string, opts: differ$0.Options): $CancellablePromise<differ$0.Result> {
    return $Call.ByID(3037149801, left, right, opts).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GenerateMock produces count random items of the given kind
 * ("name" | "address" | "phone" | "email" | "bankcard" | "lorem").
 */
export function GenerateMock(kind: string, count: number): $CancellablePromise<string[]> {
    return $Call.ByID(3256892507, kind, count).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * RegexLibrary returns the built-in common regex presets.
 */
export function RegexLibrary(): $CancellablePromise<regexx$0.Preset[]> {
    return $Call.ByID(2828730984).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * TestRegex runs a pattern against text and returns highlighted matches.
 */
export function TestRegex(pattern: string, text: string, flags: regexx$0.Flags): $CancellablePromise<regexx$0.Result> {
    return $Call.ByID(1030138621, pattern, text, flags).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = differ$0.Result.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = regexx$0.Preset.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = regexx$0.Result.createFrom;
