// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Options configures password generation.
 */
export class Options {
    "upper": boolean;
    "lower": boolean;
    "digits": boolean;
    "symbol": boolean;
    "length": number;
    "count": number;

    /** Creates a new Options instance. */
    constructor($$source: Partial<Options> = {}) {
        if (!("upper" in $$source)) {
            this["upper"] = false;
        }
        if (!("lower" in $$source)) {
            this["lower"] = false;
        }
        if (!("digits" in $$source)) {
            this["digits"] = false;
        }
        if (!("symbol" in $$source)) {
            this["symbol"] = false;
        }
        if (!("length" in $$source)) {
            this["length"] = 0;
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Options instance from a string or object.
     */
    static createFrom($$source: any = {}): Options {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Options($$parsedSource as Partial<Options>);
    }
}
