// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Parts is the decomposed URL.
 */
export class Parts {
    "protocol": string;
    "host": string;
    "port": string;
    "path": string;
    "query": QueryParam[];

    /** Creates a new Parts instance. */
    constructor($$source: Partial<Parts> = {}) {
        if (!("protocol" in $$source)) {
            this["protocol"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("query" in $$source)) {
            this["query"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Parts instance from a string or object.
     */
    static createFrom($$source: any = {}): Parts {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("query" in $$parsedSource) {
            $$parsedSource["query"] = $$createField4_0($$parsedSource["query"]);
        }
        return new Parts($$parsedSource as Partial<Parts>);
    }
}

/**
 * QueryParam is a single editable query key/value pair.
 */
export class QueryParam {
    "key": string;
    "value": string;

    /** Creates a new QueryParam instance. */
    constructor($$source: Partial<QueryParam> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryParam instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryParam {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueryParam($$parsedSource as Partial<QueryParam>);
    }
}

// Private type creation functions
const $$createType0 = QueryParam.createFrom;
const $$createType1 = $Create.Array($$createType0);
