// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Fields holds the five standard cron fields. Empty string defaults to "*".
 */
export class Fields {
    "minute": string;
    "hour": string;
    "day": string;
    "month": string;
    "weekday": string;

    /** Creates a new Fields instance. */
    constructor($$source: Partial<Fields> = {}) {
        if (!("minute" in $$source)) {
            this["minute"] = "";
        }
        if (!("hour" in $$source)) {
            this["hour"] = "";
        }
        if (!("day" in $$source)) {
            this["day"] = "";
        }
        if (!("month" in $$source)) {
            this["month"] = "";
        }
        if (!("weekday" in $$source)) {
            this["weekday"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Fields instance from a string or object.
     */
    static createFrom($$source: any = {}): Fields {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Fields($$parsedSource as Partial<Fields>);
    }
}

/**
 * Info bundles parse results.
 */
export class Info {
    "expression": string;
    "description": string;
    "nextRuns": string[];

    /** Creates a new Info instance. */
    constructor($$source: Partial<Info> = {}) {
        if (!("expression" in $$source)) {
            this["expression"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("nextRuns" in $$source)) {
            this["nextRuns"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     */
    static createFrom($$source: any = {}): Info {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nextRuns" in $$parsedSource) {
            $$parsedSource["nextRuns"] = $$createField2_0($$parsedSource["nextRuns"]);
        }
        return new Info($$parsedSource as Partial<Info>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
