// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Result groups the records resolved for a single host.
 */
export class Result {
    "host": string;
    "a": string[];
    "aaaa": string[];
    "cname": string;
    "mx": string[];
    "ns": string[];
    "txt": string[];

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("a" in $$source)) {
            this["a"] = [];
        }
        if (!("aaaa" in $$source)) {
            this["aaaa"] = [];
        }
        if (!("cname" in $$source)) {
            this["cname"] = "";
        }
        if (!("mx" in $$source)) {
            this["mx"] = [];
        }
        if (!("ns" in $$source)) {
            this["ns"] = [];
        }
        if (!("txt" in $$source)) {
            this["txt"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("a" in $$parsedSource) {
            $$parsedSource["a"] = $$createField1_0($$parsedSource["a"]);
        }
        if ("aaaa" in $$parsedSource) {
            $$parsedSource["aaaa"] = $$createField2_0($$parsedSource["aaaa"]);
        }
        if ("mx" in $$parsedSource) {
            $$parsedSource["mx"] = $$createField4_0($$parsedSource["mx"]);
        }
        if ("ns" in $$parsedSource) {
            $$parsedSource["ns"] = $$createField5_0($$parsedSource["ns"]);
        }
        if ("txt" in $$parsedSource) {
            $$parsedSource["txt"] = $$createField6_0($$parsedSource["txt"]);
        }
        return new Result($$parsedSource as Partial<Result>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
