// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DiffEntry labels an entry with its comparison state.
 */
export class DiffEntry {
    "path": string;

    /**
     * "left" | "right" | "both"
     */
    "state": string;

    /** Creates a new DiffEntry instance. */
    constructor($$source: Partial<DiffEntry> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): DiffEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiffEntry($$parsedSource as Partial<DiffEntry>);
    }
}
