// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ColorSet holds all four representations of a single color.
 */
export class ColorSet {
    "hex": string;
    "rgb": string;
    "rgba": string;
    "hsl": string;

    /** Creates a new ColorSet instance. */
    constructor($$source: Partial<ColorSet> = {}) {
        if (!("hex" in $$source)) {
            this["hex"] = "";
        }
        if (!("rgb" in $$source)) {
            this["rgb"] = "";
        }
        if (!("rgba" in $$source)) {
            this["rgba"] = "";
        }
        if (!("hsl" in $$source)) {
            this["hsl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColorSet instance from a string or object.
     */
    static createFrom($$source: any = {}): ColorSet {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColorSet($$parsedSource as Partial<ColorSet>);
    }
}
